name: Deploy Next.js

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build

      - name: Debug Build Output
        run: |
          echo "===== ROOT ====="
          ls -la

          echo ""
          echo "===== .next ====="
          ls -la .next

          echo ""
          echo "===== .next/standalone ====="
          ls -la .next/standalone || true

          echo ""
          echo "===== .next/static ====="
          ls -la .next/static || true

      - name: Prepare Deploy Files
        run: |
          rm -rf deploy
          mkdir deploy

          cp -r .next/standalone/* deploy/

          mkdir -p deploy/.next
          cp -r .next/static deploy/.next/

          if [ -d public ]; then
            cp -r public deploy/
          fi

          if [ -f package.json ]; then
            cp package.json deploy/
          fi

          echo ""
          echo "===== DEPLOY ====="
          ls -R deploy

      - name: Upload Files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: "deploy/*"
          target: "/home/tmncoid/public_html/myapp"
          strip_components: 1

      - name: Restart Node App
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            source /home/tmncoid/nodevenv/public_html/myapp/22/bin/activate

            mkdir -p /home/tmncoid/public_html/myapp/tmp
            touch /home/tmncoid/public_html/myapp/tmp/restart.txt

            echo "Application restarted."
