name: Deploy Next.js

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build

      - name: Prepare Deploy Files
        run: |
          mkdir deploy

          cp -r .next/standalone/* deploy/
          mkdir -p deploy/.next
          cp -r .next/static deploy/.next/
          cp -r public deploy/
          cp package.json deploy/
          cp server.js deploy/

      - name: Copy Files to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: "deploy/*"
          target: "/home/tmncoid/public_html/myapp"
          strip_components: 1

      - name: Restart Application
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            source /home/tmncoid/nodevenv/public_html/myapp/22/bin/activate
            touch /home/tmncoid/public_html/myapp/tmp/restart.txt || true
